const { Post } = require('../models');

const postData = [
    {"id":1,"title":"Duis mattis egestas metus.","date":"9/20/2022","user_id":3,"is_public":true,"allow_comments":true,"numComments":124},
    {"id":2,"title":"Nulla nisl.","date":"10/28/2022","user_id":9,"is_public":true,"allow_comments":false,"numComments":21},
    {"id":3,"title":"Vivamus vestibulum sagittis sapien.","date":"1/19/2022","user_id":3,"is_public":true,"allow_comments":false,"numComments":22},
    {"id":4,"title":"Duis aliquam convallis nunc.","date":"9/29/2022","user_id":3,"is_public":false,"allow_comments":false,"numComments":89},
    {"id":5,"title":"Aliquam non mauris.","date":"2/23/2023","user_id":9,"is_public":true,"allow_comments":true,"numComments":145},
    {"id":6,"title":"Donec ut mauris eget massa tempor convallis.","date":"1/22/2023","user_id":10,"is_public":false,"allow_comments":false,"numComments":105},
    {"id":7,"title":"In eleifend quam a odio.","date":"12/27/2022","user_id":4,"is_public":false,"allow_comments":true,"numComments":93},
    {"id":8,"title":"Duis ac nibh.","date":"2/1/2022","user_id":9,"is_public":false,"allow_comments":true,"numComments":94},
    {"id":9,"title":"Duis ac nibh.","date":"5/1/2023","user_id":8,"is_public":true,"allow_comments":false,"numComments":90},
    {"id":10,"title":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","date":"11/17/2022","user_id":2,"is_public":true,"allow_comments":true,"numComments":102},
    {"id":11,"title":"Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","date":"2/27/2022","user_id":4,"is_public":true,"allow_comments":false,"numComments":149},
    {"id":12,"title":"Suspendisse potenti.","date":"11/30/2022","user_id":1,"is_public":true,"allow_comments":false,"numComments":16},
    {"id":13,"title":"Suspendisse potenti.","date":"9/1/2022","user_id":9,"is_public":false,"allow_comments":false,"numComments":142},
    {"id":14,"title":"Morbi vel lectus in quam fringilla rhoncus.","date":"6/12/2022","user_id":9,"is_public":false,"allow_comments":false,"numComments":116},
    {"id":15,"title":"Sed accumsan felis.","date":"3/28/2022","user_id":4,"is_public":true,"allow_comments":false,"numComments":52},
    {"id":16,"title":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","date":"3/20/2023","user_id":8,"is_public":true,"allow_comments":true,"numComments":109},
    {"id":17,"title":"Fusce consequat.","date":"10/4/2022","user_id":4,"is_public":false,"allow_comments":false,"numComments":84},
    {"id":18,"title":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","date":"10/26/2022","user_id":8,"is_public":false,"allow_comments":false,"numComments":134},
    {"id":19,"title":"In blandit ultrices enim.","date":"7/28/2022","user_id":2,"is_public":false,"allow_comments":false,"numComments":28},
    {"id":20,"title":"Nunc nisl.","date":"7/4/2022","user_id":2,"is_public":false,"allow_comments":true,"numComments":53},
    {"id":21,"title":"Vivamus in felis eu sapien cursus vestibulum.","date":"7/24/2022","user_id":9,"is_public":true,"allow_comments":true,"numComments":4},
    {"id":22,"title":"Quisque id justo sit amet sapien dignissim vestibulum.","date":"6/10/2022","user_id":8,"is_public":false,"allow_comments":false,"numComments":123},
    {"id":23,"title":"Aliquam quis turpis eget elit sodales scelerisque.","date":"3/3/2023","user_id":5,"is_public":true,"allow_comments":true,"numComments":59},
    {"id":24,"title":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.","date":"4/1/2022","user_id":2,"is_public":true,"allow_comments":false,"numComments":125},
    {"id":25,"title":"Proin risus.","date":"6/18/2022","user_id":8,"is_public":true,"allow_comments":false,"numComments":60},
    {"id":26,"title":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","date":"4/24/2023","user_id":10,"is_public":true,"allow_comments":true,"numComments":117},
    {"id":27,"title":"Maecenas pulvinar lobortis est.","date":"5/11/2023","user_id":8,"is_public":true,"allow_comments":false,"numComments":51},
    {"id":28,"title":"Mauris ullamcorper purus sit amet nulla.","date":"6/11/2022","user_id":6,"is_public":false,"allow_comments":false,"numComments":32},
    {"id":29,"title":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.","date":"10/11/2022","user_id":4,"is_public":true,"allow_comments":true,"numComments":100},
    {"id":30,"title":"Vivamus in felis eu sapien cursus vestibulum.","date":"1/26/2023","user_id":1,"is_public":false,"allow_comments":true,"numComments":62},
    {"id":31,"title":"Morbi porttitor lorem id ligula.","date":"7/26/2022","user_id":8,"is_public":false,"allow_comments":true,"numComments":3},
    {"id":32,"title":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla.","date":"7/31/2022","user_id":6,"is_public":false,"allow_comments":false,"numComments":23},
    {"id":33,"title":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.","date":"3/31/2023","user_id":6,"is_public":true,"allow_comments":true,"numComments":114},
    {"id":34,"title":"Phasellus sit amet erat.","date":"12/16/2022","user_id":9,"is_public":true,"allow_comments":true,"numComments":148},
    {"id":35,"title":"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.","date":"4/30/2023","user_id":2,"is_public":false,"allow_comments":true,"numComments":86},
    {"id":36,"title":"Nunc rhoncus dui vel sem.","date":"3/18/2023","user_id":6,"is_public":false,"allow_comments":false,"numComments":71},
    {"id":37,"title":"Donec semper sapien a libero.","date":"11/28/2022","user_id":7,"is_public":false,"allow_comments":false,"numComments":72},
    {"id":38,"title":"In congue.","date":"4/12/2023","user_id":8,"is_public":true,"allow_comments":false,"numComments":52},
    {"id":39,"title":"Nulla justo.","date":"2/24/2023","user_id":6,"is_public":true,"allow_comments":true,"numComments":100},
    {"id":40,"title":"Aliquam sit amet diam in magna bibendum imperdiet.","date":"8/10/2022","user_id":1,"is_public":false,"allow_comments":true,"numComments":64},
    {"id":41,"title":"Nulla facilisi.","date":"1/27/2022","user_id":4,"is_public":true,"allow_comments":false,"numComments":119},
    {"id":42,"title":"Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","date":"5/11/2023","user_id":6,"is_public":false,"allow_comments":true,"numComments":115},
    {"id":43,"title":"Nulla tempus.","date":"2/24/2022","user_id":4,"is_public":true,"allow_comments":false,"numComments":80},
    {"id":44,"title":"Donec dapibus.","date":"12/24/2022","user_id":10,"is_public":false,"allow_comments":true,"numComments":69},
    {"id":45,"title":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","date":"4/12/2022","user_id":2,"is_public":false,"allow_comments":false,"numComments":29},
    {"id":46,"title":"Sed sagittis.","date":"8/6/2022","user_id":3,"is_public":false,"allow_comments":false,"numComments":90},
    {"id":47,"title":"Aliquam quis turpis eget elit sodales scelerisque.","date":"10/3/2022","user_id":3,"is_public":true,"allow_comments":false,"numComments":35},
    {"id":48,"title":"Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","date":"1/17/2022","user_id":7,"is_public":true,"allow_comments":true,"numComments":16},
    {"id":49,"title":"Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","date":"7/31/2022","user_id":8,"is_public":true,"allow_comments":false,"numComments":88},
    {"id":50,"title":"Vestibulum ac est lacinia nisi venenatis tristique.","date":"5/13/2022","user_id":9,"is_public":false,"allow_comments":true,"numComments":58}
]

const seedPosts = () => Post.bulkCreate(postData);

module.exports = seedPosts;